services:
  torch110remote:
    environment:
      MYUSERDATA: "${USER}"
    build:
      context: .
      dockerfile: Dockerfile.torchremote
    ports:
      - "7776:22" # ssh
      - "7777:7777" # gdb server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
#      - /tmp/:/tmp/
      - "C:/Users/username/Envs/:/home/Envs"
      - "D:/Thesis/:/home/Thesis/"