services:
  torch110remote:
#    image: ugurcanakyuz:torchremote
#    container_name: torchremote
#    user: root
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
#    entrypoint: /bin/bash
    environment:
      MYUSERDATA: "${USER}"
    build:
      context: .
      dockerfile: Dockerfile.torchremote
    ports:
      - "7776:22" # ssh
      - "7777:7777" # gdb server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
#      - /tmp/:/tmp/
      - "C:/Users/UgurcanAkyuz/Envs/:/home/Envs"
      - "D:/Thesis/:/home/Thesis/"