# get our base pytorch container image from torch official docker hub repository
FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime

# update package lists
RUN apt-get update -y

# update timezone for Turkey
 ENV TZ="Europe/Istanbul"

### Update packages
# tzdata - update timezone for Turkey
# lsof - for getting pid of an application, running at a port
 RUN apt-get install -y --fix-missing --no-install-recommends \
	tzdata \
	lsof

# apt-utils build-essential clang cmake gdb gdbserver openssh-server rsync - basic setup
RUN apt-get install -y --fix-missing --no-install-recommends \
  	apt-utils build-essential clang cmake gdb gdbserver openssh-server rsync\
    ffmpeg libsm6 libxext6

# clean lists
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*  && \
    apt-get clean && rm -rf /tmp/* /var/tmp/*

### Install additional libraries
COPY ../../requirements.txt /home/venv/
RUN pip install -r /home/venv/requirements.txt